CREATE TABLE IF NOT EXISTS `qingka_mall_pay_order` (
  `id`            INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `out_trade_no`  VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '商户订单号',
  `trade_no`      VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '第三方流水号',
  `tid`           INT          NOT NULL DEFAULT 0  COMMENT '店铺ID',
  `cid`           INT          NOT NULL DEFAULT 0  COMMENT '商品ID',
  `account`       VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'C端填写的账号',
  `password`      VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'C端填写的密码',
  `remark`        VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `pay_type`      VARCHAR(32)  NOT NULL DEFAULT '' COMMENT '支付方式 alipay/wxpay/qqpay',
  `money`         DECIMAL(10,2) NOT NULL DEFAULT 0  COMMENT '支付金额',
  `status`        TINYINT      NOT NULL DEFAULT 0  COMMENT '0待支付 1已支付 2已下单 -1失败',
  `order_id`      INT          NOT NULL DEFAULT 0  COMMENT '关联的业务订单ID',
  `c_uid`         INT          NOT NULL DEFAULT 0  COMMENT 'C端用户ID',
  `course_id`     VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '选择的课程ID',
  `course_name`   VARCHAR(255) NOT NULL DEFAULT '' COMMENT '选择的课程名称',
  `course_kcjs`   VARCHAR(64)  NOT NULL DEFAULT '' COMMENT '课程结束时间',
  `ip`            VARCHAR(64)  NOT NULL DEFAULT '',
  `addtime`       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `paytime`       DATETIME     NULL     DEFAULT NULL COMMENT '支付完成时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_out_trade_no` (`out_trade_no`),
  KEY `idx_tid` (`tid`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商城C端支付订单';
