ALTER TABLE `qingka_platform_config`
  ADD COLUMN `query_method` varchar(10) NOT NULL DEFAULT 'POST' COMMENT '查课请求方式' AFTER `query_path`,
  ADD COLUMN `query_body_type` varchar(16) NOT NULL DEFAULT '' COMMENT '查课请求体类型: form/json/query' AFTER `query_method`,
  ADD COLUMN `query_param_map` text COMMENT '查课参数映射JSON' AFTER `query_param_style`,
  ADD COLUMN `order_method` varchar(10) NOT NULL DEFAULT 'POST' COMMENT '下单请求方式' AFTER `order_path`,
  ADD COLUMN `order_body_type` varchar(16) NOT NULL DEFAULT '' COMMENT '下单请求体类型: form/json/query' AFTER `order_method`,
  ADD COLUMN `order_param_map` text COMMENT '下单参数映射JSON' AFTER `order_body_type`,
  ADD COLUMN `progress_body_type` varchar(16) NOT NULL DEFAULT '' COMMENT '进度请求体类型: form/json/query' AFTER `progress_method`,
  ADD COLUMN `progress_param_map` text COMMENT '进度参数映射JSON' AFTER `progress_body_type`,
  ADD COLUMN `pause_method` varchar(10) NOT NULL DEFAULT 'POST' COMMENT '暂停请求方式' AFTER `pause_path`,
  ADD COLUMN `pause_body_type` varchar(16) NOT NULL DEFAULT '' COMMENT '暂停请求体类型: form/json/query' AFTER `pause_method`,
  ADD COLUMN `pause_param_map` text COMMENT '暂停参数映射JSON' AFTER `pause_body_type`,
  ADD COLUMN `resume_method` varchar(10) NOT NULL DEFAULT 'POST' COMMENT '恢复请求方式' AFTER `resume_path`,
  ADD COLUMN `resume_body_type` varchar(16) NOT NULL DEFAULT '' COMMENT '恢复请求体类型: form/json/query' AFTER `resume_method`,
  ADD COLUMN `resume_param_map` text COMMENT '恢复参数映射JSON' AFTER `resume_body_type`,
  ADD COLUMN `change_pass_method` varchar(10) NOT NULL DEFAULT 'POST' COMMENT '改密请求方式' AFTER `change_pass_path`,
  ADD COLUMN `change_pass_body_type` varchar(16) NOT NULL DEFAULT '' COMMENT '改密请求体类型: form/json/query' AFTER `change_pass_method`,
  ADD COLUMN `change_pass_param_map` text COMMENT '改密参数映射JSON' AFTER `change_pass_body_type`,
  ADD COLUMN `resubmit_method` varchar(10) NOT NULL DEFAULT 'POST' COMMENT '补单请求方式' AFTER `resubmit_path`,
  ADD COLUMN `resubmit_body_type` varchar(16) NOT NULL DEFAULT '' COMMENT '补单请求体类型: form/json/query' AFTER `resubmit_method`,
  ADD COLUMN `resubmit_param_map` text COMMENT '补单参数映射JSON' AFTER `resubmit_body_type`,
  ADD COLUMN `log_body_type` varchar(16) NOT NULL DEFAULT '' COMMENT '日志请求体类型: form/json/query' AFTER `log_method`,
  ADD COLUMN `log_param_map` text COMMENT '日志参数映射JSON' AFTER `log_body_type`,
  ADD COLUMN `balance_body_type` varchar(16) NOT NULL DEFAULT '' COMMENT '余额请求体类型: form/json/query' AFTER `balance_method`,
  ADD COLUMN `balance_param_map` text COMMENT '余额参数映射JSON' AFTER `balance_body_type`,
  ADD COLUMN `report_method` varchar(10) NOT NULL DEFAULT 'POST' COMMENT '举报请求方式' AFTER `report_path`,
  ADD COLUMN `report_body_type` varchar(16) NOT NULL DEFAULT '' COMMENT '举报请求体类型: form/json/query' AFTER `report_method`,
  ADD COLUMN `report_param_map` text COMMENT '举报参数映射JSON' AFTER `report_body_type`,
  ADD COLUMN `get_report_method` varchar(10) NOT NULL DEFAULT 'POST' COMMENT '获取举报请求方式' AFTER `get_report_path`,
  ADD COLUMN `get_report_body_type` varchar(16) NOT NULL DEFAULT '' COMMENT '获取举报请求体类型: form/json/query' AFTER `get_report_method`,
  ADD COLUMN `get_report_param_map` text COMMENT '获取举报参数映射JSON' AFTER `get_report_body_type`;
